require 'xcodeproj'

inputs = ARGV

project_path = "#{inputs[0]}"
project = Xcodeproj::Project.open(project_path)

project.targets.each do |target|
  puts target.name
end

target = project.targets.first
group_name = "#{inputs[1]}"
parent_name = "#{inputs[2]}"
output_folder = "#{inputs[3]}"

parent_group = nil

project.groups.each do |group|
  if group.path == parent_name
    parent_group = group
    break
  end
end

output_group = parent_group.find_subpath(group_name, should_create = true)

current_files = Array.new
output_group.files.each do |file_reference|
  current_files.push(file_reference.display_name)
end

Dir[output_folder + "/*.swift"].each do |item|
  item_name = item.split("/").last
  if (current_files.include? item_name) == false
    output_group.new_reference(item)
  end
end

project.save(project_path)
